//! Interactive, local-only collection. Gold targets are copied from a
//! versioned author-supplied plan, never generated by the parser or Whisper.
mod audio;
mod store;
#[cfg(test)]
mod tests;

use std::io::{self, BufRead, IsTerminal, Write};
use std::path::PathBuf;
use std::sync::mpsc;

use clap::{Args as ClapArgs, Subcommand, ValueEnum};
use sciwhisper_eval::schema::Split;
use store::{err, ConsentKind, Result, Session};

#[derive(ClapArgs)]
pub struct Args {
    #[command(subcommand)]
    action: Action,
}

#[derive(Clone, Copy, ValueEnum)]
enum Partition {
    Train,
    Validation,
    #[value(name = "dev_holdout")]
    DevHoldout,
}
impl From<Partition> for Split {
    fn from(p: Partition) -> Self {
        match p {
            Partition::Train => Split::Train,
            Partition::Validation => Split::Validation,
            Partition::DevHoldout => Split::DevHoldout,
        }
    }
}

#[derive(Clone, Copy, ValueEnum)]
enum ConsentChoice {
    /// Signed paper form research/data/consent-ru-v2.md; required by protocol voice-v1.
    #[value(name = "consent-ru-v2")]
    RuV2,
    /// Short on-screen text; recordings stay local and never go into a published corpus.
    #[value(name = "voice-local-v1")]
    LocalV1,
}
impl From<ConsentChoice> for ConsentKind {
    fn from(c: ConsentChoice) -> Self {
        match c {
            ConsentChoice::RuV2 => ConsentKind::RuV2,
            ConsentChoice::LocalV1 => ConsentKind::LocalV1,
        }
    }
}

#[derive(Subcommand)]
enum Action {
    /// Start a local session. Consent is requested before opening a microphone.
    Start {
        #[arg(long)]
        session: PathBuf,
        /// Stable pseudonym spk01–spk99, e.g. spk01. Reuse for the same speaker.
        #[arg(long)]
        speaker: String,
        /// Assign each speaker to exactly one split across all sessions.
        #[arg(long, value_enum)]
        split: Partition,
        /// Which consent the speaker gave. Required, no default.
        #[arg(long, value_enum)]
        consent: ConsentChoice,
        /// Date of consent (YYYY-MM-DD).
        #[arg(long)]
        date: String,
        /// Short room/noise description, without names or addresses.
        #[arg(long)]
        environment: String,
        /// Author-labelled JSONL; by default the embedded dev-seed-v2 plan.
        #[arg(long)]
        tasks: Option<PathBuf>,
        #[arg(long)]
        mic: Option<String>,
        #[arg(long, default_value_t = 8, value_parser = clap::value_parser!(u64).range(1..=60))]
        seconds: u64,
    },
    /// Continue a session; already confirmed recordings remain unchanged.
    Resume {
        #[arg(long)]
        session: PathBuf,
        #[arg(long)]
        mic: Option<String>,
        #[arg(long, default_value_t = 8, value_parser = clap::value_parser!(u64).range(1..=60))]
        seconds: u64,
    },
    /// Verify saved takes and show progress, without opening the microphone.
    Status {
        #[arg(long)]
        session: PathBuf,
    },
    /// Export to a NEW local directory; no upload, no publication permission.
    Export {
        #[arg(long)]
        session: PathBuf,
        #[arg(long)]
        output: PathBuf,
    },
    /// Withdraw consent and delete this session's audio, with confirmation.
    Revoke {
        #[arg(long)]
        session: PathBuf,
    },
}

struct Console {
    lines: mpsc::Receiver<String>,
}
impl Console {
    fn open() -> Result<Self> {
        if !io::stdin().is_terminal() {
            return Err(
                "Сборщик требует интерактивный терминал; согласие нельзя передать через pipe"
                    .into(),
            );
        }
        let (tx, lines) = mpsc::sync_channel(4);
        std::thread::spawn(move || {
            let stdin = io::stdin();
            let mut stdin = stdin.lock();
            loop {
                let mut line = String::new();
                // Bound terminal input even when somebody pastes a huge file.
                let mut limited = std::io::Read::take(&mut stdin, 8193);
                match limited.read_line(&mut line) {
                    Ok(0) | Err(_) => break,
                    Ok(_) if line.len() > 8192 => break,
                    Ok(_) => {
                        if tx.send(line.trim().to_owned()).is_err() {
                            break;
                        }
                    }
                }
            }
        });
        Ok(Self { lines })
    }
    fn ask(&self, text: &str) -> Result<String> {
        print!("{text}\n> ");
        io::stdout().flush().map_err(err)?;
        self.lines
            .recv()
            .map_err(|_| "Ввод завершён; принятые записи сохранены, текущая отменена".into())
    }
}

pub fn run(args: Args) -> Result<()> {
    match args.action {
        Action::Status { session } => {
            let s = Session::open(&session)?;
            s.active()?;
            let takes = s.takes()?;
            println!("Диктор: {}. Подтверждено: {}/{}. Split: {}. Согласие: {}.\nСессия локальная, записи никуда не отправляются.", s.plan.speaker_id, takes.len(), s.plan.tasks.len(), s.plan.split.as_str(), s.plan.consent.statement_id);
            Ok(())
        }
        Action::Start {
            session,
            speaker,
            split,
            consent,
            date,
            environment,
            tasks,
            mic,
            seconds,
        } => {
            let source = match tasks {
                Some(p) => store::read_limited(&p)?,
                None => include_bytes!("../../../research/data/dev-seed-v2.jsonl").to_vec(),
            };
            let kind = ConsentKind::from(consent);
            let plan = store::plan(&source, split.into(), speaker, date, environment, kind)?;
            let console = Console::open()?;
            println!(
                "{}\nЗаданий: {}. Папка: {}\nПримеры: {}",
                kind.notice(),
                plan.tasks.len(),
                session.display(),
                plan.tasks
                    .iter()
                    .take(4)
                    .map(|r| r.human_transcript.as_str())
                    .collect::<Vec<_>>()
                    .join("; ")
            );
            let answer = console.ask(&kind.question())?;
            if !kind.accepts(&answer) {
                println!("Запись отменена.");
                return Ok(());
            }
            let s = Session::create(&session, plan)?;
            collect(&s, &console, mic, seconds)
        }
        Action::Resume {
            session,
            mic,
            seconds,
        } => {
            let s = Session::open(&session)?;
            s.active()?;
            let console = Console::open()?;
            println!(
                "Продолжение сессии {} ({})\n{}",
                s.plan.speaker_id,
                s.plan.split.as_str(),
                s.plan.consent_kind()?.notice()
            );
            if console.ask("Продолжить локальную запись? Введите ДА.")? != "ДА"
            {
                return Ok(());
            }
            collect(&s, &console, mic, seconds)
        }
        Action::Export { session, output } => {
            let s = Session::open(&session)?;
            s.active()?;
            let console = Console::open()?;
            println!("Будет создана копия голоса и текста в {}. После отзыва согласия эту копию нужно удалить отдельно. Экспорт не разрешает передачу или публикацию.", output.display());
            if console.ask("Введите ЭКСПОРТ для создания локальной копии.")? != "ЭКСПОРТ"
            {
                return Ok(());
            }
            let count = s.export(&output)?;
            println!("Экспортировано {count} записей. Пакет содержит dataset.jsonl, audio/, consent.txt и pack.json с SHA-256.\nДля распознавания используйте ingest; для проверки — validate-dataset. Все asr_hypotheses пока пусты.");
            Ok(())
        }
        Action::Revoke { session } => {
            let s = Session::open(&session)?;
            let console = Console::open()?;
            println!("Будут удалены все аудиозаписи и подтверждения из {}. Ранее экспортированные копии останутся.", session.display());
            if console.ask("Введите УДАЛИТЬ, чтобы отозвать согласие и удалить записи.")?
                != "УДАЛИТЬ"
            {
                return Ok(());
            }
            s.revoke()?;
            println!("Согласие отозвано, записи этой сессии удалены. Восстановить их из приложения нельзя; экспортированные копии удалите отдельно.");
            Ok(())
        }
    }
}

fn choose_mic(console: &Console, configured: Option<String>) -> Result<String> {
    let devices = audio::microphones()?;
    if devices.is_empty() {
        return Err(
            "Нет доступного микрофона. Сессию можно продолжить после его подключения".into(),
        );
    }
    if let Some(mic) = configured {
        if devices.iter().any(|d| d == &mic) {
            return Ok(mic);
        }
        return Err("Выбранный микрофон не найден; продолжите сессию с другим --mic".into());
    }
    println!("Выберите микрофон (его системное имя будет сохранено):");
    for (i, name) in devices.iter().enumerate() {
        println!("{}: {name}", i + 1);
    }
    let index = console
        .ask("Номер микрофона:")?
        .parse::<usize>()
        .map_err(|_| "Нужен номер из списка")?;
    devices
        .get(index.wrapping_sub(1))
        .cloned()
        .ok_or("Нет такого номера микрофона".into())
}

fn collect(session: &Session, console: &Console, mic: Option<String>, seconds: u64) -> Result<()> {
    let accepted = session.takes()?;
    if accepted.len() == session.plan.tasks.len() {
        println!("Все задания уже записаны; можно выполнить export.");
        return Ok(());
    }
    let mic = choose_mic(console, mic)?;
    for (idx, task) in session.plan.tasks.iter().enumerate() {
        if accepted.contains_key(&idx) {
            continue;
        }
        loop {
            println!(
                "\nЗадание {}/{}: {}",
                idx + 1,
                session.plan.tasks.len(),
                task.human_transcript
            );
            match console
                .ask("Enter — запись; s — пропустить; q — сохранить прогресс и выйти.")?
                .as_str()
            {
                "q" => return Ok(()),
                "s" => break,
                "" => {}
                _ => continue,
            }
            let wav = match audio::record(&mic, seconds, &console.lines) {
                Ok(Some(wav)) => wav,
                Ok(None) => continue,
                Err(error) => {
                    eprintln!("{error}");
                    continue;
                }
            };
            let facts = sciwhisper_asr::corpus::describe_wav(wav.path()).map_err(err)?;
            println!("Сохранено временно: {:.1} с. Детектор речи: {}. Начало и конец записи не обрезаны.", facts.duration_secs, if facts.has_speech { "речь обнаружена" } else { "речь не обнаружена — проверьте звук" });
            let mut played = false;
            loop {
                match console.ask("p — прослушать; a — подтвердить; r — перезаписать; q — выйти, отбросив эту попытку.")?.as_str() {
                    "p" => match audio::playback(wav.path()) { Ok(()) => played = true, Err(e) => eprintln!("{e}") },
                    "a" if !played => println!("Сначала прослушайте запись командой p."),
                    "a" => {
                        println!("Подтверждаемый текст: {}", task.human_transcript);
                        if console.ask("Вы произнесли именно этот текст целиком? Введите ТОЧНО. При оговорке используйте r.")? == "ТОЧНО" {
                            session.accept(idx, wav.path(), &task.human_transcript, &mic)?;
                            println!("Запись подтверждена.");
                            break;
                        }
                    },
                    "r" => break,
                    "q" => return Ok(()),
                    _ => {},
                }
            }
            // Only a committed take advances the plan. Retakes never replace
            // a prior confirmation and temporary audio is RAII-owned.
            if session.root.join(format!("takes/{idx:04}")).exists() {
                break;
            }
        }
    }
    println!("Проход завершён. status покажет прогресс; resume вернётся к пропущенным заданиям; export создаст локальный пакет.");
    Ok(())
}
