#!/usr/bin/env python3
"""Regenerates packaging/THIRD-PARTY-LICENSES.json from the lockfile.

Run after adding or updating a dependency:

    python3 packaging/collect-licenses.py

The result is committed. `licenses.rs` in sciwhisper-eval then checks two
things on every test run, without a network: that the file still describes
exactly the packages Cargo.lock names, and that every licence in it is one
this project has decided it can ship. A new dependency therefore fails the
build until somebody has looked at its licence — which is the point.
"""

import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "packaging" / "THIRD-PARTY-LICENSES.json"


def main() -> int:
    raw = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if raw.returncode != 0:
        sys.stderr.write(raw.stderr)
        return raw.returncode
    meta = json.loads(raw.stdout)

    workspace = {member.split()[0] for member in meta["workspace_members"]} | {
        p["name"] for p in meta["packages"] if p.get("source") is None
    }

    packages = []
    for package in sorted(meta["packages"], key=lambda p: (p["name"], p["version"])):
        if package["name"] in workspace and package.get("source") is None:
            continue  # our own crates
        entry = {
            "name": package["name"],
            "version": package["version"],
            "license": package.get("license"),
        }
        if package.get("license") is None:
            entry["license_file"] = package.get("license_file")
        packages.append(entry)

    OUT.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "comment": (
                    "Every third-party crate in this workspace's dependency graph, with "
                    "the licence it declares. Generated by packaging/collect-licenses.py "
                    "and checked by sciwhisper-eval's licenses.rs, which fails when a "
                    "package appears that is not listed here or carries a licence this "
                    "project has not decided it can ship."
                ),
                "packages": packages,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"{len(packages)} third-party packages written to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
